import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

type WhatsAppAlert = { id: string; created_at: string; category: 'help' | 'pickup'; contact_phone: string }
const label = (category: WhatsAppAlert['category']) => category === 'help' ? 'Ayuda solicitada' : 'Recojo / motorizado'
const formatDate = (value: string) => new Intl.DateTimeFormat('es-PE', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value))

export function WhatsAppAlerts() {
  const [alerts, setAlerts] = useState<WhatsAppAlert[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [handlingId, setHandlingId] = useState<string | null>(null)
  const loadAlerts = useCallback(async () => { const { data, error } = await supabase.from('whatsapp_staff_alerts').select('id, created_at, category, contact_phone').eq('status', 'pending').order('created_at', { ascending: false }).limit(100); if (error) setMessage('No se pudieron cargar las alertas de WhatsApp.'); else { setAlerts((data ?? []) as WhatsAppAlert[]); setMessage('') }; setLoading(false) }, [])
  useEffect(() => { void loadAlerts(); const timer = window.setInterval(() => void loadAlerts(), 30_000); return () => window.clearInterval(timer) }, [loadAlerts])
  const markHandled = async (alertId: string) => { setHandlingId(alertId); setMessage(''); try { const { data, error } = await supabase.auth.getSession(); if (error || !data.session) throw new Error('Vuelve a iniciar sesión.'); const response = await fetch('/.netlify/functions/whatsapp-alert-handle', { method: 'POST', headers: { Authorization: `Bearer ${data.session.access_token}`, 'content-type': 'application/json' }, body: JSON.stringify({ alertId }) }); const result = await response.json().catch(() => null) as { message?: string } | null; if (!response.ok) throw new Error(result?.message || 'No se pudo atender la alerta.'); await loadAlerts() } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo atender la alerta.') } finally { setHandlingId(null) } }
  return <section className="staff-section whatsapp-alerts"><div className="staff-section-title"><div><h2>Alertas de WhatsApp</h2><p>{loading ? 'Cargando alertas…' : alerts.length ? `${alerts.length} pendiente(s)` : 'No hay alertas pendientes.'}</p></div><button type="button" className="staff-secondary" onClick={() => void loadAlerts()} disabled={loading}>Actualizar</button></div>{message && <p className="staff-message" role="status">{message}</p>}{!loading && alerts.length > 0 && <ul className="whatsapp-alert-list">{alerts.map((alert) => <li key={alert.id}><div><strong>{label(alert.category)}</strong><span>{alert.contact_phone}</span><small>{formatDate(alert.created_at)}</small></div><button type="button" className="staff-primary" disabled={handlingId === alert.id} onClick={() => void markHandled(alert.id)}>{handlingId === alert.id ? 'Guardando…' : 'Marcar atendida'}</button></li>)}</ul>}</section>
}
