import { useCallback, useEffect, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'

type AlertCategory = 'help' | 'pickup' | 'pedido' | 'pedido_fuera_de_horario' | 'club' | 'horario' | 'ubicacion' | 'agradecimiento' | 'generico'
type WhatsAppAlert = { id: string; created_at: string; category: AlertCategory; contact_phone: string }
const labels: Record<AlertCategory, string> = { help: 'Ayuda solicitada', pickup: 'Recojo / motorizado', pedido: 'Pedido recibido', pedido_fuera_de_horario: 'Pedido fuera de horario', club: 'Consulta sobre el club', horario: 'Consulta de horario', ubicacion: 'Consulta de ubicación', agradecimiento: 'Mensaje de agradecimiento', generico: 'Mensaje recibido' }
const formatDate = (value: string) => new Intl.DateTimeFormat('es-PE', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value))

export function WhatsAppAlerts() {
  const [alerts, setAlerts] = useState<WhatsAppAlert[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [handlingId, setHandlingId] = useState<string | null>(null); const [soundEnabled, setSoundEnabled] = useState(false); const audioContextRef = useRef<AudioContext | null>(null); const voiceTimeoutRef = useRef<number | null>(null)
  const enableSound = useCallback(async () => { const AudioContextConstructor = window.AudioContext || window.webkitAudioContext; if (!AudioContextConstructor) { setMessage('Este navegador no permite alertas de sonido.'); return }; const context = audioContextRef.current ?? new AudioContextConstructor(); audioContextRef.current = context; await context.resume(); setSoundEnabled(true); setMessage('Sonido activado en este navegador.') }, [])
  const playAlertSound = useCallback((category: AlertCategory) => { const context = audioContextRef.current; if (!soundEnabled || !context || context.state !== 'running') return; const now = context.currentTime; const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.type = 'square'; for (let index = 0; index < 5; index += 1) { const start = now + index * 0.34; oscillator.frequency.setValueAtTime(index % 2 ? 660 : 880, start); gain.gain.setValueAtTime(0.0001, start); gain.gain.exponentialRampToValueAtTime(0.28, start + 0.02); gain.gain.exponentialRampToValueAtTime(0.0001, start + 0.27) }; oscillator.connect(gain).connect(context.destination); oscillator.start(now); oscillator.stop(now + 1.72); if (category !== 'help' || !('speechSynthesis' in window)) return; window.speechSynthesis.cancel(); if (voiceTimeoutRef.current) window.clearTimeout(voiceTimeoutRef.current); voiceTimeoutRef.current = window.setTimeout(() => { const phrase = 'Un cliente necesita tu ayuda.'; const speech = new SpeechSynthesisUtterance(`${phrase} ${phrase} ${phrase}`); speech.lang = 'es-PE'; speech.rate = 0.88; speech.pitch = 1.1; speech.volume = 1; window.speechSynthesis.speak(speech) }, 1800) }, [soundEnabled])
  const loadAlerts = useCallback(async () => { const { data, error } = await supabase.from('whatsapp_staff_alerts').select('id, created_at, category, contact_phone').eq('status', 'pending').order('created_at', { ascending: false }).limit(100); if (error) setMessage('No se pudieron cargar las alertas de WhatsApp.'); else { setAlerts((data ?? []) as WhatsAppAlert[]); setMessage('') }; setLoading(false) }, [])
  useEffect(() => { void loadAlerts(); const channel = supabase.channel('whatsapp-staff-alerts').on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'whatsapp_staff_alerts' }, (payload) => { const alert = payload.new as WhatsAppAlert; setAlerts((current) => current.some((item) => item.id === alert.id) ? current : [alert, ...current]); setLoading(false); playAlertSound(alert.category) }).subscribe(); const timer = window.setInterval(() => void loadAlerts(), 30_000); return () => { window.clearInterval(timer); if (voiceTimeoutRef.current) window.clearTimeout(voiceTimeoutRef.current); void supabase.removeChannel(channel) } }, [loadAlerts, playAlertSound])
  const markHandled = async (alertId: string) => { setHandlingId(alertId); setMessage(''); try { const { data, error } = await supabase.auth.getSession(); if (error || !data.session) throw new Error('Vuelve a iniciar sesión.'); const response = await fetch('/.netlify/functions/whatsapp-alert-handle', { method: 'POST', headers: { Authorization: `Bearer ${data.session.access_token}`, 'content-type': 'application/json' }, body: JSON.stringify({ alertId }) }); const result = await response.json().catch(() => null) as { message?: string } | null; if (!response.ok) throw new Error(result?.message || 'No se pudo atender la alerta.'); await loadAlerts() } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo atender la alerta.') } finally { setHandlingId(null) } }
  return <section className="staff-section whatsapp-alerts"><div className="staff-section-title"><div><h2>Alertas de WhatsApp</h2><p>{loading ? 'Cargando alertas…' : alerts.length ? `${alerts.length} pendiente(s)` : 'No hay alertas pendientes.'}</p></div><div><button type="button" className="staff-secondary" onClick={() => void enableSound()}>{soundEnabled ? 'Sonido activado' : 'Activar sonido'}</button><button type="button" className="staff-secondary" onClick={() => void loadAlerts()} disabled={loading}>Actualizar</button></div></div>{message && <p className="staff-message" role="status">{message}</p>}{!loading && alerts.length > 0 && <ul className="whatsapp-alert-list">{alerts.map((alert) => <li key={alert.id}><div><strong>{labels[alert.category] || 'Mensaje recibido'}</strong><span>{alert.contact_phone}</span><small>{formatDate(alert.created_at)}</small></div><button type="button" className="staff-primary" disabled={handlingId === alert.id} onClick={() => void markHandled(alert.id)}>{handlingId === alert.id ? 'Guardando…' : 'Marcar atendida'}</button></li>)}</ul>}</section>
}
