import type { ReactNode } from 'react'

type LegalPageProps = { title: string; children: ReactNode }

function LegalPage({ title, children }: LegalPageProps) {
  return <main className="app-shell legal-page"><header className="topbar"><a className="brand" href="/" aria-label="Volver a The Black Cat"><span className="brand-mark" aria-hidden="true">✦</span><span><strong>THE BLACK CAT</strong><small>ROCK BAR</small></span></a></header><article className="legal-content"><p className="eyebrow">THE BLACK CAT – ROCK BAR</p><h1>{title}</h1>{children}</article><footer><span>THE BLACK CAT · ROCK BAR</span><div className="footer-links"><a className="complaints-book-link" href="/libro-de-reclamaciones">Libro de Reclamaciones</a><a href="/terminos-y-condiciones">Términos y Condiciones</a><a href="/politica-de-privacidad">Política de Privacidad</a></div><span>Delivery &amp; recojo</span></footer></main>
}

export function TermsAndConditions() {
  return <LegalPage title="Términos y Condiciones de Uso"><p className="legal-subtitle">The Black Cat – Rock Bar</p><section><h2>Datos del proveedor</h2><p><strong>HERITAGE GROUP S.A.C.</strong><br />RUC: 20610407499<br />Nombre comercial: The Black Cat – Rock Bar<br />Grau 184, Barranca, Perú<br /><a href="mailto:contacto@theblackcatrockbar.com">contacto@theblackcatrockbar.com</a></p></section><section><h2>1. Aceptación de términos</h2><p>Al utilizar esta plataforma, aceptas estos Términos y Condiciones de Uso.</p></section><section><h2>2. Uso de la plataforma</h2><p>La plataforma permite revisar el menú y realizar pedidos de The Black Cat – Rock Bar.</p></section><section><h2>3. Productos y disponibilidad</h2><p>Los productos incluyen descripción, ingredientes, imágenes referenciales y precios. Su disponibilidad depende del stock existente.</p></section><section><h2>4. Proceso de compra</h2><p>Los pedidos pueden realizarse bajo dos modalidades: recojo en local o delivery.</p></section><section><h2>5. Modalidad recojo en local</h2><p>El recojo se realiza en Grau 184, Barranca.</p></section><section><h2>6. Modalidad delivery</h2><p>Para delivery se solicita el nombre del receptor, teléfono, dirección y las referencias necesarias. Los tiempos pueden variar por distancia, tráfico, volumen de pedidos y factores externos.</p></section><section><h2>7. Pagos electrónicos</h2><p>Los pagos electrónicos son procesados mediante Culqi. The Black Cat no almacena datos sensibles de tarjetas.</p></section><section><h2>8. Comprobantes de pago</h2><p>Se puede solicitar boleta con DNI o factura con RUC.</p></section><section><h2>9. Protección de datos personales</h2><p>Los datos personales se tratan conforme a nuestra Política de Privacidad y únicamente para las finalidades necesarias del servicio.</p></section><section><h2>10. Responsabilidad del usuario</h2><p>El usuario debe proporcionar datos veraces y completos para la correcta atención del pedido.</p></section><section><h2>11. Limitación de responsabilidad</h2><p>The Black Cat no será responsable por demoras o incumplimientos derivados de circunstancias ajenas a su control razonable.</p></section><section><h2>12. Modificaciones de términos</h2><p>Podemos actualizar estos términos cuando sea necesario. La versión vigente será publicada en esta página.</p></section><section><h2>13. Contacto</h2><p>Para consultas, escríbenos a <a href="mailto:contacto@theblackcatrockbar.com">contacto@theblackcatrockbar.com</a>.</p></section></LegalPage>
}

export function PrivacyPolicy() {
  return <LegalPage title="Política de Privacidad"><p className="legal-subtitle">The Black Cat – Rock Bar</p><section><h2>Responsable</h2><p><strong>HERITAGE GROUP S.A.C.</strong><br />RUC: 20610407499<br /><a href="mailto:contacto@theblackcatrockbar.com">contacto@theblackcatrockbar.com</a></p></section><section><h2>1. Información recopilada</h2><p>Podemos recopilar nombres y apellidos, DNI o CE cuando corresponda, correo electrónico, teléfono, dirección de entrega e información de pedidos.</p></section><section><h2>2. Finalidad del uso</h2><p>Usamos estos datos para procesar pedidos, coordinar delivery, emitir comprobantes, enviar confirmaciones y atender consultas y reclamos.</p></section><section><h2>3. Pagos</h2><p>Culqi procesa los pagos electrónicos. The Black Cat no almacena datos sensibles de tarjetas.</p></section><section><h2>4. Protección de información</h2><p>Aplicamos medidas razonables para proteger la información personal frente a accesos, usos o divulgaciones no autorizados.</p></section><section><h2>5. Compartición de datos</h2><p>Compartimos datos únicamente cuando es necesario para procesar pagos, coordinar delivery o cumplir obligaciones legales.</p></section><section><h2>6. Derechos del usuario</h2><p>El usuario puede solicitar información, actualización o rectificación de sus datos mediante nuestro correo de contacto.</p></section><section><h2>7. Uso de cookies y tecnologías similares</h2><p>Podemos utilizar cookies y tecnologías similares para el funcionamiento y mejora de la plataforma.</p></section><section><h2>8. Cambios en la política</h2><p>Podemos actualizar esta Política de Privacidad. La versión vigente se mantendrá publicada en esta página.</p></section></LegalPage>
}
